/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Abnormal;
import Model.Encounter;
import Model.EncounterHistory;

import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prasannanimbalkar
 */
public class AbnormalPanel extends javax.swing.JPanel {

    /**
     * Creates new form AbnormalPanel
     */
    
    EncounterHistory encounterHistoryList;
    int column;
    ArrayList<Encounter> filteredEncounter;
    ArrayList<Encounter> filteredCommunity1;
    ArrayList<Encounter> filteredCommunity2;
    ArrayList<Encounter> filteredCommunity3;
    ArrayList<Encounter> filteredCommunity4;
    
    public AbnormalPanel(EncounterHistory encounterHistoryList) {
        initComponents();
        this.encounterHistoryList = encounterHistoryList;
//       populateTableAB1();
        filterBP() ;
        //populateCommunity(tblAbnormal2,  filteredEncounter);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Abnormal = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        btnCommunity = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAbnormal1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAbnormal2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAbnormal3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAbnormal4 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Abnormal1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        Abnormal.setFont(new java.awt.Font("Tamil MN", 1, 20)); // NOI18N
        Abnormal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Abnormal.setText("Abnormal Vitals");
        Abnormal.setToolTipText("");

        txtCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityActionPerformed(evt);
            }
        });

        btnCommunity.setBackground(new java.awt.Color(51, 153, 255));
        btnCommunity.setForeground(new java.awt.Color(255, 255, 255));
        btnCommunity.setText("Community");
        btnCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunityActionPerformed(evt);
            }
        });

        tblAbnormal1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Address", "Area", "City", "Temp.", "Blood Press.", "Pulse", "Resp. rate", "Weight", "date"
            }
        ));
        tblAbnormal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAbnormal1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAbnormal1);

        tblAbnormal2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Address", "Area", "City", "Temp.", "Blood Press.", "Pulse", "Resp. rate", "Weight", "date"
            }
        ));
        tblAbnormal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAbnormal2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAbnormal2);

        tblAbnormal3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Address", "Area", "City", "Temp.", "Blood Press.", "Pulse", "Resp. rate", "Weight", "date"
            }
        ));
        tblAbnormal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAbnormal3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblAbnormal3);

        tblAbnormal4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Address", "Area", "City", "Temp.", "Blood Press.", "Pulse", "Resp. rate", "Weight", "date"
            }
        ));
        tblAbnormal4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAbnormal4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblAbnormal4);

        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("List for Ages- 0 to 15");

        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("List for Ages- 16 to 30");

        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("List for Ages- 31 to 50");

        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("List for Ages- 51 to 90");

        Abnormal1.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        Abnormal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Abnormal1.setText("Normal Blood Pressure range 80 - 120");
        Abnormal1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCommunity)
                .addGap(18, 18, 18)
                .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Abnormal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Abnormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Abnormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Abnormal1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCommunity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblAbnormal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAbnormal3MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tblAbnormal3MouseClicked

    private void txtCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityActionPerformed

    private void btnCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunityActionPerformed
        // TODO add your handling code here:
        filteredCommunity1 = new ArrayList<Encounter>();
        filteredCommunity2 = new ArrayList<Encounter>();
        filteredCommunity3 = new ArrayList<Encounter>();
        filteredCommunity4 = new ArrayList<Encounter>();
        String community = txtCommunity.getText();
        for(Encounter en : filteredEncounter) {
               if(en.getVitalPatientInformation().getCommunity().equalsIgnoreCase(community) && (en.getVitalPatientInformation().getAge() >=0 && en.getVitalPatientInformation().getAge() <=15)){
                   filteredCommunity1.add(en);
               }else if(en.getVitalPatientInformation().getCommunity().equalsIgnoreCase(community) && (en.getVitalPatientInformation().getAge() >=16 && en.getVitalPatientInformation().getAge() <=30)){
                   filteredCommunity2.add(en);
               }else if(en.getVitalPatientInformation().getCommunity().equalsIgnoreCase(community) && (en.getVitalPatientInformation().getAge() >=31 && en.getVitalPatientInformation().getAge() <=50)){
                   filteredCommunity3.add(en);
               }else if(en.getVitalPatientInformation().getCommunity().equalsIgnoreCase(community) && (en.getVitalPatientInformation().getAge() >=51 && en.getVitalPatientInformation().getAge() <=90)){
                   filteredCommunity4.add(en);
               }else{
                   
               }
                   
            }
        
        
        populateCommunity(tblAbnormal1,  filteredCommunity1);
        populateCommunity(tblAbnormal2,  filteredCommunity2);
        populateCommunity(tblAbnormal3,  filteredCommunity3);
        populateCommunity(tblAbnormal4,  filteredCommunity4);
        txtCommunity.setText("");
    }//GEN-LAST:event_btnCommunityActionPerformed

    private void tblAbnormal2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAbnormal2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAbnormal2MouseClicked

    private void tblAbnormal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAbnormal1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAbnormal1MouseClicked

    private void tblAbnormal4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAbnormal4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAbnormal4MouseClicked

    private void filterBP() {                                               
        // TODO add your handling code here:
        filteredEncounter = new ArrayList<Encounter>();

        for(Encounter en : encounterHistoryList.getEncounterHistoryList()) {
                if(en.getVitals().getBloodPressure() <= 80 ||  en.getVitals().getBloodPressure() >= 120) {
                    filteredEncounter.add(en);
                }
            }
    }
    
//    private void filterCommunity(){
//        filteredCommunity = new ArrayList<Encounter>();
//        String community = txtCommunity.getText();
//        for(Encounter en : encounterHistoryList.getEncounterHistoryList()) {
//               if(en.getVitalPatientInformation().getCommunity() == community)
//                filteredCommunity.add(en);
//                
//            }
//    }
    
    
//    private void populateTableAB1() {
//        
//        DefaultTableModel model = (DefaultTableModel) tblAbnormal3.getModel();
//        model.setRowCount(0);
//        filterBP() ;
//        
//        for (Encounter cd : filteredEncounter){
//            
//            
//            Object[] row = new Object[11];
//            row[0] = cd;
////                    .getAvaliablity();
//            row[1] = cd.getVitalPatientInformation().getAge();
//            row[2] = cd.getVitalPatientInformation().getHouse();
//            row[3] = cd.getVitalPatientInformation().getCommunity();
//            row[4] = cd.getVitalPatientInformation().getCity();
//            row[5] = cd.getVitals().getTemperature();
//            row[6] = cd.getVitals().getBloodPressure();
//            row[7] = cd.getVitals().getPulse();
//            row[8] = cd.getVitals().getRespiratoryRate();
//            row[9] = cd.getVitals().getWeightInKilos();
//            row[10] = cd.getVitals().getDate();
//            
//            model.addRow(row);
//          
//            
//            
//        }
//
//    }
    
    private void populateCommunity(javax.swing.JTable table, ArrayList<Encounter> list) {
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        
        
        for (Encounter cd : list) {
            
            
            Object[] row = new Object[11];
            row[0] = cd;
//                    .getAvaliablity();
            row[1] = cd.getVitalPatientInformation().getAge();
            row[2] = cd.getVitalPatientInformation().getHouse();
            row[3] = cd.getVitalPatientInformation().getCommunity();
            row[4] = cd.getVitalPatientInformation().getCity();
            row[5] = cd.getVitals().getTemperature();
            row[6] = cd.getVitals().getBloodPressure();
            row[7] = cd.getVitals().getPulse();
            row[8] = cd.getVitals().getRespiratoryRate();
            row[9] = cd.getVitals().getWeightInKilos();
            row[10] = cd.getVitals().getDate();
            
            model.addRow(row); 
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abnormal;
    private javax.swing.JLabel Abnormal1;
    private javax.swing.JButton btnCommunity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblAbnormal1;
    private javax.swing.JTable tblAbnormal2;
    private javax.swing.JTable tblAbnormal3;
    private javax.swing.JTable tblAbnormal4;
    private javax.swing.JTextField txtCommunity;
    // End of variables declaration//GEN-END:variables
}
