/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Praz
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonJPanel
     */
    Person person;
    public CreatePersonJPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbAccNum = new javax.swing.JLabel();
        txtbAccNum = new javax.swing.JTextField();
        lbllicenseNum = new javax.swing.JLabel();
        txtlicenseNum = new javax.swing.JTextField();
        lblvIdNum = new javax.swing.JLabel();
        txtvIdNum = new javax.swing.JTextField();
        lbldIdNum = new javax.swing.JLabel();
        txtdIdNum = new javax.swing.JTextField();
        lblLinkedIn = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JTextField();
        lblTelNum = new javax.swing.JLabel();
        txtIPA = new javax.swing.JTextField();
        txtTelNum = new javax.swing.JTextField();
        lblIPA = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        txtFaxNum = new javax.swing.JTextField();
        lbleMail = new javax.swing.JLabel();
        txteMail = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblMRN = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblGeoArea = new javax.swing.JLabel();
        txtGeoArea = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblhpbNum = new javax.swing.JLabel();
        txthpbNum = new javax.swing.JTextField();
        lblUID = new javax.swing.JLabel();
        txtUID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblBioId = new javax.swing.JLabel();
        btnBioId = new javax.swing.JButton();

        setBackground(new java.awt.Color(247, 246, 246));

        lblbAccNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblbAccNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbAccNum.setText("Bank Account Number:");

        txtbAccNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtbAccNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbAccNumFocusLost(evt);
            }
        });
        txtbAccNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbAccNumActionPerformed(evt);
            }
        });

        lbllicenseNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lbllicenseNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbllicenseNum.setText("License Number:");

        txtlicenseNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtlicenseNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlicenseNumFocusLost(evt);
            }
        });
        txtlicenseNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicenseNumActionPerformed(evt);
            }
        });

        lblvIdNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblvIdNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblvIdNum.setText("Vehical Serial Number:");

        txtvIdNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtvIdNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtvIdNumFocusLost(evt);
            }
        });
        txtvIdNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvIdNumActionPerformed(evt);
            }
        });

        lbldIdNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lbldIdNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbldIdNum.setText("Device Serial Number:");

        txtdIdNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtdIdNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdIdNumFocusLost(evt);
            }
        });
        txtdIdNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdIdNumActionPerformed(evt);
            }
        });

        lblLinkedIn.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblLinkedIn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLinkedIn.setText("LinkedIn:");

        txtLinkedIn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtLinkedIn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLinkedInFocusLost(evt);
            }
        });
        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });

        lblTelNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblTelNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTelNum.setText("Phone Number:");

        txtIPA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtIPA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIPAFocusLost(evt);
            }
        });
        txtIPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAActionPerformed(evt);
            }
        });

        txtTelNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTelNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelNumFocusLost(evt);
            }
        });
        txtTelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelNumActionPerformed(evt);
            }
        });
        txtTelNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelNumKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelNumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelNumKeyTyped(evt);
            }
        });

        lblIPA.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblIPA.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblIPA.setText("IP Address:");

        lblFaxNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblFaxNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFaxNum.setText("Fax Number:");

        txtFaxNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtFaxNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFaxNumFocusLost(evt);
            }
        });
        txtFaxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumActionPerformed(evt);
            }
        });

        lbleMail.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lbleMail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbleMail.setText("Email:");

        txteMail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txteMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txteMailFocusLost(evt);
            }
        });
        txteMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteMailActionPerformed(evt);
            }
        });
        txteMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txteMailKeyReleased(evt);
            }
        });

        lblSSN.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSSN.setText("Social Security Number:");

        txtSSN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSSN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSSNFocusLost(evt);
            }
        });
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblMRN.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblMRN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMRN.setText("Medical Record Number:");

        txtMRN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtMRN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMRNFocusLost(evt);
            }
        });
        txtMRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMRNActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(102, 102, 255));
        lblTitle.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Person");
        lblTitle.setToolTipText("");
        lblTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblName.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Name:");
        lblName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblGeoArea.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblGeoArea.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGeoArea.setText("City:");

        txtGeoArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtGeoArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGeoAreaFocusLost(evt);
            }
        });
        txtGeoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeoAreaActionPerformed(evt);
            }
        });

        lblDOB.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDOB.setText("Date of Birth:");

        txtDOB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDOBFocusLost(evt);
            }
        });
        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        lblhpbNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblhpbNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblhpbNum.setText("Health Plan Numbaer:");

        txthpbNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txthpbNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txthpbNumFocusLost(evt);
            }
        });
        txthpbNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthpbNumActionPerformed(evt);
            }
        });

        lblUID.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblUID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUID.setText("Unique Identification Number:");

        txtUID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUIDFocusLost(evt);
            }
        });
        txtUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUIDActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblBioId.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblBioId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBioId.setText("Image:");

        btnBioId.setText("Add");
        btnBioId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBioIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGeoArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbleMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFaxNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMRN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblhpbNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txteMail)
                    .addComponent(txtMRN)
                    .addComponent(txtName)
                    .addComponent(txtGeoArea)
                    .addComponent(txtTelNum)
                    .addComponent(txtFaxNum)
                    .addComponent(txtSSN)
                    .addComponent(txthpbNum)
                    .addComponent(txtDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIPA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLinkedIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbldIdNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblvIdNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbllicenseNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblbAccNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUID, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(lblBioId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtlicenseNum, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtvIdNum)
                    .addComponent(txtdIdNum)
                    .addComponent(txtLinkedIn)
                    .addComponent(txtIPA)
                    .addComponent(txtUID)
                    .addComponent(txtbAccNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBioId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGeoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGeoArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDOB)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelNum)
                            .addComponent(txtTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFaxNum)
                            .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbleMail)
                            .addComponent(txteMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSSN)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMRN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthpbNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblhpbNum)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbllicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvIdNum)
                            .addComponent(txtvIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldIdNum)
                            .addComponent(txtdIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLinkedIn)
                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIPA)
                            .addComponent(txtIPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUID)
                            .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBioId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBioId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(16, 16, 16)
                .addComponent(btnSave)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtbAccNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbAccNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbAccNumActionPerformed

    private void txtlicenseNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicenseNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicenseNumActionPerformed

    private void txtvIdNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvIdNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvIdNumActionPerformed

    private void txtdIdNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdIdNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdIdNumActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtIPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAActionPerformed

    private void txtTelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNumActionPerformed

    private void txtTelNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelNumKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNumKeyReleased

    private void txtUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUIDActionPerformed

    private void txtFaxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(jLabel1.getText().length()==0){
            person.setName(txtName.getText());
            person.setGeoArea(txtGeoArea.getText());
            person.setDOB(txtDOB.getText());
            person.setTelNum(Integer.parseInt(txtTelNum.getText()));
            person.setFaxNum(Integer.parseInt(txtFaxNum.getText()));
            person.seteMail(txteMail.getText());
            person.setSSN(txtSSN.getText());
            person.setMRN(Integer.parseInt(txtMRN.getText()));
            person.sethpbNum(Integer.parseInt(txthpbNum.getText()));
            person.setbAccNum(Integer.parseInt(txtbAccNum.getText()));
            person.setlicenseNum(txtlicenseNum.getText());
            person.setvIdNum(txtvIdNum.getText());
            person.setdIdNum(txtdIdNum.getText());
            person.setLinkedIn(txtLinkedIn.getText());
            person.setIPA(txtIPA.getText());
            person.setUID(txtUID.getText());
        
            JOptionPane.showMessageDialog(this, "Person Information Saved.");
        }else{
            JOptionPane.showMessageDialog(this, "Please Enter Valid Details");
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txteMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteMailActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtMRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMRNActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtGeoAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeoAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeoAreaActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txthpbNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthpbNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthpbNumActionPerformed

    private void txtTelNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelNumFocusGained
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtTelNumFocusGained

    private void txtFaxNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFaxNumFocusLost
        // TODO add your handling code here:
        validateNumber(txtFaxNum,lblFaxNum, jLabel1, "Fax Number");
    }//GEN-LAST:event_txtFaxNumFocusLost

    private void txtTelNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelNumFocusLost
        // TODO add your handling code here:
        validatePhone(txtTelNum,jLabel1,"Phone Number");
    }//GEN-LAST:event_txtTelNumFocusLost

    private void txtTelNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelNumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNumKeyPressed

    private void txteMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txteMailFocusLost
        // TODO add your handling code here:
        validateMail(txteMail,jLabel1,"Email ID");
    }//GEN-LAST:event_txteMailFocusLost

    private void txteMailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteMailKeyReleased
        // TODO add your handling code here:
//        String input = txteMail.getText();
//        String number = input.replaceFirst("(\\d{3})(\\d{3})(\\d+)", "($1) $2-$3");
//        return number.toString(txteMail);
    }//GEN-LAST:event_txteMailKeyReleased

    private void txtTelNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelNumKeyTyped
        
    }//GEN-LAST:event_txtTelNumKeyTyped

    private void txtIPAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIPAFocusLost
        // TODO add your handling code here:
            validateIP(txtIPA,jLabel1,"IP");
            
    }//GEN-LAST:event_txtIPAFocusLost

    private void txtSSNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSSNFocusLost
        // TODO add your handling code here:
        validateSSN(txtSSN,lblSSN, jLabel1, "SSN Number");
    }//GEN-LAST:event_txtSSNFocusLost

    private void txtbAccNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbAccNumFocusLost
        // TODO add your handling code here:
        validateBank(txtbAccNum, lblbAccNum, jLabel1,"Bank Account Number");
    }//GEN-LAST:event_txtbAccNumFocusLost

    private void txtDOBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBFocusLost
        // TODO add your handling code here:
        validateDate(txtDOB,lblDOB, jLabel1);
    }//GEN-LAST:event_txtDOBFocusLost

    private void txtMRNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMRNFocusLost
        // TODO add your handling code here:
        validateNumber(txtMRN,lblMRN, jLabel1, "MRN");
    }//GEN-LAST:event_txtMRNFocusLost

    private void btnBioIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBioIdActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        int showOpenDialouge = browseImageFile.showOpenDialog(null);
        if(showOpenDialouge == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, "Done");
            person.setBioId(selectedImagePath);
            btnBioId.setBackground(Color.green);
            btnBioId.setText("Uploaded");
    }//GEN-LAST:event_btnBioIdActionPerformed
   }
    
    
    private void txthpbNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txthpbNumFocusLost
        // TODO add your handling code here:
        validateNumber(txthpbNum,lblhpbNum, jLabel1, "Health Plan Number");
    }//GEN-LAST:event_txthpbNumFocusLost

    private void txtlicenseNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlicenseNumFocusLost
        // TODO add your handling code here:
        validateNumber(txtlicenseNum,lbllicenseNum, jLabel1, "License Number");
    }//GEN-LAST:event_txtlicenseNumFocusLost

    private void txtLinkedInFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLinkedInFocusLost
        // TODO add your handling code here:
        validateLinkedIN(txtLinkedIn ,lblLinkedIn , jLabel1);
    }//GEN-LAST:event_txtLinkedInFocusLost

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        validateName(txtName,lblName, jLabel1,"Name");
    }//GEN-LAST:event_txtNameFocusLost

    private void txtGeoAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGeoAreaFocusLost
        // TODO add your handling code here:
        validateCity(txtGeoArea,lblGeoArea, jLabel1,"City");
    }//GEN-LAST:event_txtGeoAreaFocusLost

    private void txtvIdNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvIdNumFocusLost
        // TODO add your handling code here:
        validateNumber(txtvIdNum,lblvIdNum , jLabel1, "Vehical number");
    }//GEN-LAST:event_txtvIdNumFocusLost

    private void txtdIdNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdIdNumFocusLost
        // TODO add your handling code here:
        validateNumber(txtdIdNum,lbldIdNum , jLabel1, "Device number");
    }//GEN-LAST:event_txtdIdNumFocusLost

    private void txtUIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUIDFocusLost
        // TODO add your handling code here:
        validateNumber(txtUID,lblUID , jLabel1, "UID number");
    }//GEN-LAST:event_txtUIDFocusLost
    
    
    //custom code for validation
    Border redline = BorderFactory.createLineBorder(Color.red);
    Border noline = BorderFactory.createLineBorder(Color.black);
    Border greenline = BorderFactory.createLineBorder(Color.green);
    public void validatePhone(JTextField field, JLabel label, String name){

        if(field.getText().length()==0)
        {
            label.setText("");
            field.setBorder(noline);
            lblTelNum.setForeground(Color.black);
        }else if(field.getText().matches(".*[^0-9].*")){
            lblTelNum.setForeground(Color.red);
            field.setBorder(redline);
            label.setText("Invalid " + name);
            
        }else if(field.getText().length()!=10){
            lblTelNum.setForeground(Color.red);
            field.setBorder(redline);
            label.setText("Check lenght of " + name);
        }else{
            lblTelNum.setForeground(Color.black);
            field.setBorder(greenline);
            label.setText("");
        }
   }
    
    public void validateMail(JTextField field, JLabel label, String name){

        
        if(field.getText().length()==0)
        {
            label.setText("");
            field.setBorder(noline);
            lbleMail.setForeground(Color.black);
        }else if(!field.getText().matches("^(.+)@(.+)$")){
            lbleMail.setForeground(Color.red);
            field.setBorder(redline);
            label.setText("Invalid " + name);
            
        }else{
            lbleMail.setForeground(Color.black);
            field.setBorder(greenline);
            label.setText("");
        }
    }
//    
    public void validateIP(JTextField field, JLabel label, String name){

        if(field.getText().length()==0)
        {
            label.setText("");
            field.setBorder(noline);
            lblIPA.setForeground(Color.black);
        }else if(!field.getText().matches("^(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})$")){
            lblIPA.setForeground(Color.red);
            field.setBorder(redline);
            label.setText("Invalid " + name);
            
        }else{
            lblIPA.setForeground(Color.black);
            field.setBorder(greenline);
            label.setText("");
        }
       
    }
    
    
    public void validateNumber(JTextField field,JLabel label2, JLabel label, String name){

        if(field.getText().length()==0)
        {
            label.setText("");
            field.setBorder(noline);
            label2.setForeground(Color.black);
        }else if(field.getText().matches(".*[^0-9].*")){
            label2.setForeground(Color.red);
            field.setBorder(redline);
            label.setText("Invalid " + name);
            
        }else{
            label2.setForeground(Color.black);
            field.setBorder(greenline);
            label.setText("");
        }
    }
    
    
    public void validateDate(JTextField field,JLabel label2, JLabel label) {
        
        if(field.getText().length()==0)
        {
            label.setText("");
            field.setBorder(noline);
            label2.setForeground(Color.black);
        }else if(!field.getText().matches("^(0?[1-9]|[12][0-9]|3[01])[\\/\\-](0?[1-9]|1[012])[\\/\\-]\\d{4}$")){
            label2.setForeground(Color.red);
            field.setBorder(redline);
            label.setText("Enter Date in DD/MM/YYYY format");
            
        }else{
            label2.setForeground(Color.black);
            field.setBorder(greenline);
            label.setText("");
        }
    }
    
    
    public void validateSSN(JTextField field,JLabel label2, JLabel label, String name){

        if(field.getText().length()==0)
        {
            label.setText("");
            field.setBorder(noline);
            label2.setForeground(Color.black);
        }else if(field.getText().matches("^(\\d{3}-?\\d{2}-?\\d{4}|XXX-XX-XXXX)$")){
            label2.setForeground(Color.black);
            field.setBorder(greenline);
            label.setText("");
        }else{
            label2.setForeground(Color.black);
            field.setBorder(redline);
            label.setText("SSN should be of the from XXX-XX-XXXX");
        }
   
    }
    //
    
    public void validateLinkedIN(JTextField field,JLabel label2, JLabel label){

        if(field.getText().length()==0)
        {
            label.setText("");
            field.setBorder(noline);
            label2.setForeground(Color.black);
        }else if(field.getText().matches("^https:\\/\\/[a-z]{2,3}\\.linkedin\\.com\\/.*$")){
            label2.setForeground(Color.black);
            field.setBorder(greenline);
            label.setText("");
        }else{
            label2.setForeground(Color.black);
            field.setBorder(redline);
            label.setText("LinkedIn should be of the from https://www.linkedin.com/sometext");
        }
   
    }
    
    public void validateBank(JTextField field, JLabel label2,JLabel label, String name){

        if(field.getText().length()==0)
        {
            label.setText("");
            field.setBorder(noline);
            label2.setForeground(Color.black);
        }else if(field.getText().matches(".*[^0-9].*")){
            label2.setForeground(Color.red);
            field.setBorder(redline);
            label.setText("Invalid " + name);
            
        }else if(field.getText().length()!=10){
            label2.setForeground(Color.red);
            field.setBorder(redline);
            label.setText("Check lenght of " + name +". Should be 10 digits");
        }else{
            label2.setForeground(Color.black);
            field.setBorder(greenline);
            label.setText("");
        }
   }
    
     public void validateName(JTextField field,JLabel label2, JLabel label,String name){

        if(field.getText().length()==0)
        {
            label.setText("");
            field.setBorder(noline);
            label2.setForeground(Color.black);
        }else if(!field.getText().matches("\\w+")){
            label2.setForeground(Color.red);
            field.setBorder(redline);
            label.setText("Invalid " + name);
        }else{
            label2.setForeground(Color.black);
            field.setBorder(greenline);
            label.setText("");
        }
   
    }
     
     
      public void validateCity(JTextField field,JLabel label2, JLabel label,String name){

        if(field.getText().length()==0)
        {
            label.setText("");
            field.setBorder(noline);
            label2.setForeground(Color.black);
        }else if(!field.getText().matches(".*[^0-9].*")){
            label2.setForeground(Color.red);
            field.setBorder(redline);
            label.setText("Invalid " + name);
        }else{
            label2.setForeground(Color.black);
            field.setBorder(greenline);
            label.setText("");
        }
   
    }
      
      
        
 

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBioId;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBioId;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblGeoArea;
    private javax.swing.JLabel lblIPA;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMRN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUID;
    private javax.swing.JLabel lblbAccNum;
    private javax.swing.JLabel lbldIdNum;
    private javax.swing.JLabel lbleMail;
    private javax.swing.JLabel lblhpbNum;
    private javax.swing.JLabel lbllicenseNum;
    private javax.swing.JLabel lblvIdNum;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtGeoArea;
    private javax.swing.JTextField txtIPA;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelNum;
    private javax.swing.JTextField txtUID;
    private javax.swing.JTextField txtbAccNum;
    private javax.swing.JTextField txtdIdNum;
    private javax.swing.JTextField txteMail;
    private javax.swing.JTextField txthpbNum;
    private javax.swing.JTextField txtlicenseNum;
    private javax.swing.JTextField txtvIdNum;
    // End of variables declaration//GEN-END:variables
}
