/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import static java.lang.Integer.parseInt;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
/**
 *
 * @author Praz
 */
public class DisplayPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayPersonJPanel
     */
    Person person;
    
    public DisplayPersonJPanel(Person person) {
        initComponents();
        this.person = person;
        displayPerson();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbAccNum = new javax.swing.JLabel();
        txtbAccNum = new javax.swing.JTextField();
        lbllicenseNum = new javax.swing.JLabel();
        txtlicenseNum = new javax.swing.JTextField();
        lblvIdNum = new javax.swing.JLabel();
        txtvIdNum = new javax.swing.JTextField();
        lbldIdNum = new javax.swing.JLabel();
        txtdIdNum = new javax.swing.JTextField();
        lblLinkedIn = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JTextField();
        lblTelNum = new javax.swing.JLabel();
        txtIPA = new javax.swing.JTextField();
        txtTelNum = new javax.swing.JTextField();
        lblIPA = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        txtUID = new javax.swing.JTextField();
        txtFaxNum = new javax.swing.JTextField();
        lblUID = new javax.swing.JLabel();
        lbleMail = new javax.swing.JLabel();
        txteMail = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblMRN = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblGeoArea = new javax.swing.JLabel();
        txtGeoArea = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblhpbNum = new javax.swing.JLabel();
        txthpbNum = new javax.swing.JTextField();
        lblBioId = new javax.swing.JLabel();
        btnBioId = new javax.swing.JButton();

        setBackground(new java.awt.Color(247, 246, 246));

        lblbAccNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblbAccNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblbAccNum.setText("Bank Account Number:");

        txtbAccNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtbAccNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbAccNumActionPerformed(evt);
            }
        });

        lbllicenseNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lbllicenseNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbllicenseNum.setText("License Number:");

        txtlicenseNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtlicenseNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicenseNumActionPerformed(evt);
            }
        });

        lblvIdNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblvIdNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblvIdNum.setText("Vehical Serial Number:");

        txtvIdNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtvIdNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvIdNumActionPerformed(evt);
            }
        });

        lbldIdNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lbldIdNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbldIdNum.setText("Device Serial Number:");

        txtdIdNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtdIdNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdIdNumActionPerformed(evt);
            }
        });

        lblLinkedIn.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblLinkedIn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLinkedIn.setText("LinkedIn:");

        txtLinkedIn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });

        lblTelNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblTelNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTelNum.setText("Phone Number:");

        txtIPA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtIPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAActionPerformed(evt);
            }
        });

        txtTelNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTelNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelNumFocusLost(evt);
            }
        });
        txtTelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelNumActionPerformed(evt);
            }
        });
        txtTelNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelNumKeyReleased(evt);
            }
        });

        lblIPA.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblIPA.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblIPA.setText("IP Address:");

        lblFaxNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblFaxNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFaxNum.setText("Fax Number:");

        txtUID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUIDActionPerformed(evt);
            }
        });

        txtFaxNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtFaxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumActionPerformed(evt);
            }
        });

        lblUID.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblUID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUID.setText("Unique Identification Number:");

        lbleMail.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lbleMail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbleMail.setText("Email:");

        txteMail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txteMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteMailActionPerformed(evt);
            }
        });

        lblSSN.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSSN.setText("Social Security Number:");

        txtSSN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblMRN.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblMRN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMRN.setText("Medical Record Number:");

        txtMRN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtMRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMRNActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(102, 102, 255));
        lblTitle.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Display Person");
        lblTitle.setToolTipText("");
        lblTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblName.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Name:");
        lblName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblGeoArea.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblGeoArea.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGeoArea.setText("City:");

        txtGeoArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtGeoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeoAreaActionPerformed(evt);
            }
        });

        lblDOB.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDOB.setText("Date of Birth:");

        txtDOB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        lblhpbNum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblhpbNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblhpbNum.setText("Health Plan Numbaer:");

        txthpbNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txthpbNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthpbNumActionPerformed(evt);
            }
        });

        lblBioId.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblBioId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBioId.setText("Image:");

        btnBioId.setText("See Image");
        btnBioId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBioIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGeoArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbleMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFaxNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMRN, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(lblhpbNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txteMail)
                    .addComponent(txtMRN)
                    .addComponent(txtName)
                    .addComponent(txtGeoArea)
                    .addComponent(txtTelNum)
                    .addComponent(txtFaxNum)
                    .addComponent(txtSSN)
                    .addComponent(txthpbNum)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLinkedIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblvIdNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbllicenseNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblbAccNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldIdNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUID, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblBioId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtlicenseNum)
                    .addComponent(txtvIdNum)
                    .addComponent(txtdIdNum)
                    .addComponent(txtLinkedIn)
                    .addComponent(txtIPA)
                    .addComponent(txtUID)
                    .addComponent(txtbAccNum, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(btnBioId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGeoArea)
                            .addComponent(txtGeoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDOB)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFaxNum)
                            .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbleMail)
                            .addComponent(txteMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSN)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbllicenseNum)
                            .addComponent(txtlicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvIdNum)
                            .addComponent(txtvIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldIdNum)
                            .addComponent(txtdIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLinkedIn)
                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIPA)
                            .addComponent(txtIPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUID)
                            .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMRN)
                        .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBioId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBioId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthpbNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhpbNum))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txthpbNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthpbNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthpbNumActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtGeoAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeoAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeoAreaActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtMRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMRNActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txteMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteMailActionPerformed

    private void txtFaxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumActionPerformed

    private void txtUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUIDActionPerformed

    private void txtTelNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelNumKeyReleased
        // TODO add your handling code here:

        //        String Num = txtTelNum.getText();
        //        if(Num == ("^(0-9)*$")){
            //            txtTelNum.setBackground(Color.GREEN);
            //        }else{
            //            txtTelNum.setBackground(Color.green);
            //        }
    }//GEN-LAST:event_txtTelNumKeyReleased

    private void txtTelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNumActionPerformed

    private void txtbAccNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbAccNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbAccNumActionPerformed

    private void txtIPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtdIdNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdIdNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdIdNumActionPerformed

    private void txtvIdNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvIdNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvIdNumActionPerformed

    private void txtlicenseNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicenseNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicenseNumActionPerformed

    private void txtTelNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelNumFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNumFocusLost

    private void btnBioIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBioIdActionPerformed
        // TODO add your handling code here:

        JFrame frame = new JFrame();
        ImageIcon icon = new ImageIcon(person.getBioId());
        JLabel label = new JLabel(icon);
        frame.add(label);
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true); 

    }//GEN-LAST:event_btnBioIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBioId;
    private javax.swing.JLabel lblBioId;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblGeoArea;
    private javax.swing.JLabel lblIPA;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMRN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUID;
    private javax.swing.JLabel lblbAccNum;
    private javax.swing.JLabel lbldIdNum;
    private javax.swing.JLabel lbleMail;
    private javax.swing.JLabel lblhpbNum;
    private javax.swing.JLabel lbllicenseNum;
    private javax.swing.JLabel lblvIdNum;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtGeoArea;
    private javax.swing.JTextField txtIPA;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelNum;
    private javax.swing.JTextField txtUID;
    private javax.swing.JTextField txtbAccNum;
    private javax.swing.JTextField txtdIdNum;
    private javax.swing.JTextField txteMail;
    private javax.swing.JTextField txthpbNum;
    private javax.swing.JTextField txtlicenseNum;
    private javax.swing.JTextField txtvIdNum;
    // End of variables declaration//GEN-END:variables
        
    private void displayPerson() {
        
        txtName.setText(person.getName());
        txtGeoArea.setText(person.getGeoArea());
        txtDOB.setText(person.getDOB());
        txtTelNum.setText(String.valueOf(person.getTelNum()));
        txtFaxNum.setText(String.valueOf(person.getFaxNum()));
        txteMail.setText(person.geteMail());
        txtSSN.setText(String.valueOf(person.getSSN()));
        txtMRN.setText(String.valueOf(person.getMRN()));
        txthpbNum.setText(String.valueOf(person.gethpbNum()));
        txtbAccNum.setText(String.valueOf(person.getbAccNum()));
        txtlicenseNum.setText(String.valueOf(person.getlicenseNum()));
        txtvIdNum.setText(person.getvIdNum());
        txtdIdNum.setText(person.getdIdNum());
        txtLinkedIn.setText(person.getLinkedIn());
        txtIPA.setText(person.getIPA());
        txtUID.setText(person.getUID());
        
        
        
    }
}
